---

name: Integration
on:
    pull_request:
    push:
        branches:
            - master
            - main

jobs:
    integration:
        name: Integration
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: actions/setup-go@v5

            - name: Build and run tests
              run: |
                go build
                go test -v -coverprofile=coverage.out ./...

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v4.0.1
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
